version: '3.8'

services:
  flappybird-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flappybird-web
    environment:
      - PORT=5000
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      # Persist high scores
      - ./highscore.json:/app/highscore.json
      # Mount templates and static for development (optional)
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

